version: '3.3'

services:
  master:
    build:
      context: .
      args:
        USER: ${dUSER}
        GROUP: ${dGROUP}
        UID: ${dUID}
        GID: ${dGID}
    image: leonardoedgar/wheeled-robot-master
    container_name: master
    network_mode: "host"
    environment:
      - DISPLAY=unix$DISPLAY
    shm_size: 256M
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../simulation.py:/home/${dUSER}/simulation.py
    stop_signal: SIGINT
    command: sleep infinity
